#define CHAR_WIDTH 6
#define CHAR_HEIGHT 10

#define EDIT_WIDTH CHAR_WIDTH * 7
#define EDIT_HEIGHT CHAR_HEIGHT + 5

#define EDIT_DISTANCE 5

#define TOP_OFFSET 30
#define A_MATRIX_OFFSET 5
#define B_MATRIX_OFFSET 860
#define RESULT_MATRIX_OFFSET 430